[[constraint]]
   name = "github.com/kataras/iris"
   version = "10.2.0"

[[constraint]]
   name = "github.com/disintegration/imaging"
   version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
